name: project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.2
  firebase_auth: ^4.4.2
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutterfire_ui: ^0.4.3+20
  http: ^0.13.5
  image_picker: ^0.8.7+4
  onesignal_flutter: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_avatar.png